%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%ALL CODE TAKEN DIRECTLY FROM JJ SCIENCE PAPER, then edited by me
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Apply Constraints to Control Parameters during Optimization

% This function is used during human-in-the-loop optimization. After CMA-ES
% generated a generation of conditions in the form of [peak torque, 2* peak
% time, rise time, 2* fall time], each set of condition is put through this
% function to be hard constraint.

% INPUTS
% original params: One set of control parameters randomly generated by
% CMA-ES. It is a 4x1 or 1x4 vector made of [peak torque, 2* peak time,
% rise time, 2* fall time] or [peak torque, 2*peak time, rise time, 2* fall
% time]'.
% maxTorque: The maximum allowed peak torque of the current subject. It is
% usually set as 0.825*(subject body mass), but can be changed based on
% subject feedback. Normally it's between [0.8 1]*(subject body mass).

% OUTPUTS
% params: Control parameters [peak torque, 2*peak time, rise time, 2*fall
% time]' after constraints applied.

% This function constrains peak torque to be [0 maxTorque]. 2*peak time is
% constraint to be at least 10% of strid period. When peak torque is
% smaller or equal to 75% of maxTroque, 2*peak time is upper bounded at 110%
% stride period. When peak torque is in[75% 100%] of maxTorque, the upper
% bound of 2*peak time is linearly interploted between 100% and 110% ob
% stride period. Both rise time and 2*fall time is bounded in [10% 40%] of
% stride period. Further more, when peak time + fall time >65% of stride
% period, we force fall time = 65- peak time. Then if peak time - rise time
% < 5% of stride period, ew enforce rise time = peak time -5.

% Copyright@Juanjuan Zhang, Steven H Collins 11/30/2016





function params = apply_constraints(original_params, max_torque, min_torque)
params = zeros(length(original_params), 1);

param1min=min_torque/max_torque; %For testing
param1max=1; %Peak torque can be anything from 0 to 1 because 1 corresponds to max torque. 
%Max torque is an input because we use to use it as a constraint, istead of
%just scaling from 0 to 1. 
% param2min=0; 
% param2max=1; %Rise time can be anything 0 to 100% so 0 to 1

%Currently, parameter 1 is the peak torque, and parameter 2 is the rise
%time as percent of stance time. 

% assert params to be column vector;
if iscolumn(original_params)
    params = original_params;
else
    params = original_params';
end

params(1,1) = max(param1min, params(1,1));  %Forces param 1 to be at least param1min
params(1,1) = min(param1max, params(1,1));  %Forces param 1 to be no bigger than param1max
% params(2,1) = max(param2min, params(2,1));
% params(2,1) = min(param2max, params(2,1));



return;
